/* eslint-disable @typescript-eslint/no-explicit-any */
// One-off script: заполнить work_catalog расширенными данными
// Запуск: npx tsx scripts/seed-work-catalog.ts

import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const works: Array<{
  code: string;
  name: string;
  category: string;
  norm_minutes: number;
  norm_minutes_valdai: number;
  default_price_client: string;
  internal_cost_rate: string;
}> = [
  // ТО и регламент
  {
    code: 'TO_1',
    name: 'ТО-1 (масло, фильтры воздух/топливо)',
    category: 'ТО и регламент',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'TO_2',
    name: 'ТО-2 (полное)',
    category: 'ТО и регламент',
    norm_minutes: 300,
    norm_minutes_valdai: 360,
    default_price_client: '7500',
    internal_cost_rate: '3750',
  },
  {
    code: 'OIL_CHANGE',
    name: 'Замена масла двигателя',
    category: 'ТО и регламент',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'AIR_FILTER',
    name: 'Замена воздушного фильтра',
    category: 'ТО и регламент',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'FUEL_FILTER',
    name: 'Замена топливного фильтра',
    category: 'ТО и регламент',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'CABIN_FILTER',
    name: 'Замена салонного фильтра',
    category: 'ТО и регламент',
    norm_minutes: 15,
    norm_minutes_valdai: 15,
    default_price_client: '375',
    internal_cost_rate: '188',
  },
  {
    code: 'ANTIFREEZE',
    name: 'Замена антифриза (ОЖ)',
    category: 'ТО и регламент',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'BRAKE_FLUID',
    name: 'Замена тормозной жидкости',
    category: 'ТО и регламент',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'GUR_FLUID',
    name: 'Замена жидкости ГУР',
    category: 'ТО и регламент',
    norm_minutes: 30,
    norm_minutes_valdai: 45,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  // Двигатель
  {
    code: 'TIMING_BELT',
    name: 'Замена ремня ГРМ',
    category: 'Двигатель',
    norm_minutes: 240,
    norm_minutes_valdai: 300,
    default_price_client: '6000',
    internal_cost_rate: '3000',
  },
  {
    code: 'TIMING_CHAIN',
    name: 'Замена цепи ГРМ',
    category: 'Двигатель',
    norm_minutes: 360,
    norm_minutes_valdai: 420,
    default_price_client: '9000',
    internal_cost_rate: '4500',
  },
  {
    code: 'ENGINE_DIAG',
    name: 'Диагностика двигателя',
    category: 'Двигатель',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'HEAD_GASKET',
    name: 'Замена прокладки ГБЦ',
    category: 'Двигатель',
    norm_minutes: 480,
    norm_minutes_valdai: 540,
    default_price_client: '12000',
    internal_cost_rate: '6000',
  },
  {
    code: 'VALVE_ADJUST',
    name: 'Регулировка клапанов',
    category: 'Двигатель',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'INJECTORS',
    name: 'Замена форсунок',
    category: 'Двигатель',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'GLOW_PLUGS',
    name: 'Замена свечей накала',
    category: 'Двигатель',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'SPARK_PLUGS',
    name: 'Замена свечей зажигания',
    category: 'Двигатель',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'TURBO_REPLACE',
    name: 'Замена турбокомпрессора',
    category: 'Двигатель',
    norm_minutes: 360,
    norm_minutes_valdai: 420,
    default_price_client: '9000',
    internal_cost_rate: '4500',
  },
  {
    code: 'TURBO_DIAG',
    name: 'Диагностика турбины',
    category: 'Двигатель',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'EGR_CLEAN',
    name: 'Чистка клапана EGR',
    category: 'Двигатель',
    norm_minutes: 90,
    norm_minutes_valdai: 90,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'ENGINE_MOUNT',
    name: 'Замена подушек двигателя',
    category: 'Двигатель',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'RADIATOR_REPLACE',
    name: 'Замена радиатора охлаждения',
    category: 'Двигатель',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  {
    code: 'THERMOSTAT',
    name: 'Замена термостата',
    category: 'Двигатель',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'WATER_PUMP',
    name: 'Замена водяной помпы',
    category: 'Двигатель',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'BELT_DRIVE',
    name: 'Замена приводного ремня (навесного)',
    category: 'Двигатель',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'BELT_TENSIONER',
    name: 'Замена натяжителя ремня',
    category: 'Двигатель',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'SEALS_GASKETS',
    name: 'Замена сальников / прокладок двигателя',
    category: 'Двигатель',
    norm_minutes: 240,
    norm_minutes_valdai: 300,
    default_price_client: '6000',
    internal_cost_rate: '3000',
  },
  // Трансмиссия
  {
    code: 'CLUTCH',
    name: 'Замена сцепления (комплект)',
    category: 'Трансмиссия',
    norm_minutes: 300,
    norm_minutes_valdai: 360,
    default_price_client: '7500',
    internal_cost_rate: '3750',
  },
  {
    code: 'CLUTCH_CABLE',
    name: 'Замена троса сцепления',
    category: 'Трансмиссия',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'CLUTCH_CYLINDER',
    name: 'Замена гл./раб. цилиндра сцепления',
    category: 'Трансмиссия',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'GEARBOX_OIL',
    name: 'Замена масла КПП',
    category: 'Трансмиссия',
    norm_minutes: 45,
    norm_minutes_valdai: 60,
    default_price_client: '1125',
    internal_cost_rate: '563',
  },
  {
    code: 'REAR_AXLE_OIL',
    name: 'Замена масла заднего моста',
    category: 'Трансмиссия',
    norm_minutes: 45,
    norm_minutes_valdai: 60,
    default_price_client: '1125',
    internal_cost_rate: '563',
  },
  {
    code: 'GEARBOX_REPLACE',
    name: 'Замена КПП',
    category: 'Трансмиссия',
    norm_minutes: 360,
    norm_minutes_valdai: 420,
    default_price_client: '9000',
    internal_cost_rate: '4500',
  },
  {
    code: 'GEARBOX_ADJUST',
    name: 'Регулировка КПП / кулисы',
    category: 'Трансмиссия',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'CARDAN_REPLACE',
    name: 'Замена карданного вала',
    category: 'Трансмиссия',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  {
    code: 'CARDAN_CROSS',
    name: 'Замена крестовины кардана',
    category: 'Трансмиссия',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'HUB_BEARING_FRONT',
    name: 'Замена ступичного подшипника (перед.)',
    category: 'Трансмиссия',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'HUB_BEARING_REAR',
    name: 'Замена ступичного подшипника (зад.)',
    category: 'Трансмиссия',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  // Ходовая
  {
    code: 'BRAKE_PADS_FRONT',
    name: 'Замена тормозных колодок (пер.)',
    category: 'Ходовая',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'BRAKE_PADS_REAR',
    name: 'Замена тормозных колодок (зад.)',
    category: 'Ходовая',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'BRAKE_DISCS_FRONT',
    name: 'Замена тормозных дисков (пер.)',
    category: 'Ходовая',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'BRAKE_DRUMS_REAR',
    name: 'Замена тормозных барабанов (зад.)',
    category: 'Ходовая',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  {
    code: 'SHOCK_FRONT',
    name: 'Замена амортизаторов передних',
    category: 'Ходовая',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  {
    code: 'SHOCK_REAR',
    name: 'Замена амортизаторов задних',
    category: 'Ходовая',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'ALIGNMENT',
    name: 'Регулировка развал-схождения',
    category: 'Ходовая',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'SUSPENSION_DIAG',
    name: 'Диагностика ходовой',
    category: 'Ходовая',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'BALL_JOINT',
    name: 'Замена шаровой опоры',
    category: 'Ходовая',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'TIE_ROD',
    name: 'Замена рулевой тяги',
    category: 'Ходовая',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'TIE_ROD_END',
    name: 'Замена рулевого наконечника',
    category: 'Ходовая',
    norm_minutes: 45,
    norm_minutes_valdai: 60,
    default_price_client: '1125',
    internal_cost_rate: '563',
  },
  {
    code: 'SILENTBLOCK_FRONT',
    name: 'Замена сайлентблоков передней подвески',
    category: 'Ходовая',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'SILENTBLOCK_REAR',
    name: 'Замена сайлентблоков задней подвески',
    category: 'Ходовая',
    norm_minutes: 150,
    norm_minutes_valdai: 180,
    default_price_client: '3750',
    internal_cost_rate: '1875',
  },
  {
    code: 'SPRING_REPLACE',
    name: 'Замена рессоры / пружины',
    category: 'Ходовая',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'STABILIZER_BUSH',
    name: 'Замена втулок стабилизатора',
    category: 'Ходовая',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'STABILIZER_LINK',
    name: 'Замена стоек стабилизатора',
    category: 'Ходовая',
    norm_minutes: 45,
    norm_minutes_valdai: 60,
    default_price_client: '1125',
    internal_cost_rate: '563',
  },
  {
    code: 'STEERING_RACK',
    name: 'Замена рулевой рейки',
    category: 'Ходовая',
    norm_minutes: 240,
    norm_minutes_valdai: 300,
    default_price_client: '6000',
    internal_cost_rate: '3000',
  },
  {
    code: 'STEERING_PUMP',
    name: 'Замена насоса ГУР',
    category: 'Ходовая',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'WHEEL_BEARING',
    name: 'Замена подшипника колеса',
    category: 'Ходовая',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'ABS_SENSOR',
    name: 'Замена датчика ABS',
    category: 'Ходовая',
    norm_minutes: 30,
    norm_minutes_valdai: 45,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  // Электрика
  {
    code: 'ALTERNATOR',
    name: 'Замена генератора',
    category: 'Электрика',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'STARTER',
    name: 'Замена стартера',
    category: 'Электрика',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'ELECTRIC_DIAG',
    name: 'Диагностика электрики',
    category: 'Электрика',
    norm_minutes: 90,
    norm_minutes_valdai: 90,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'BATTERY_REPLACE',
    name: 'Замена АКБ',
    category: 'Электрика',
    norm_minutes: 15,
    norm_minutes_valdai: 15,
    default_price_client: '375',
    internal_cost_rate: '188',
  },
  {
    code: 'WIRING_REPAIR',
    name: 'Ремонт проводки (поиск обрыва/КЗ)',
    category: 'Электрика',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'HEADLIGHT_REPLACE',
    name: 'Замена фары / фонаря',
    category: 'Электрика',
    norm_minutes: 30,
    norm_minutes_valdai: 45,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'LAMP_REPLACE',
    name: 'Замена ламп (фара/габарит/стоп)',
    category: 'Электрика',
    norm_minutes: 15,
    norm_minutes_valdai: 15,
    default_price_client: '375',
    internal_cost_rate: '188',
  },
  {
    code: 'IGNITION_COIL',
    name: 'Замена катушки зажигания',
    category: 'Электрика',
    norm_minutes: 30,
    norm_minutes_valdai: 45,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'WIRING_HARNESS',
    name: 'Замена жгута проводки',
    category: 'Электрика',
    norm_minutes: 180,
    norm_minutes_valdai: 240,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  // Кузов и салон
  {
    code: 'BODY_REPAIR',
    name: 'Кузовной ремонт (мелкий)',
    category: 'Кузов',
    norm_minutes: 240,
    norm_minutes_valdai: 300,
    default_price_client: '6000',
    internal_cost_rate: '3000',
  },
  {
    code: 'BODY_PAINT',
    name: 'Покраска элемента кузова',
    category: 'Кузов',
    norm_minutes: 360,
    norm_minutes_valdai: 420,
    default_price_client: '9000',
    internal_cost_rate: '4500',
  },
  {
    code: 'GLASS_REPLACE',
    name: 'Замена стекла (лобовое/боковое)',
    category: 'Кузов',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'DOOR_HANDLE',
    name: 'Замена ручки двери / замка',
    category: 'Кузов',
    norm_minutes: 30,
    norm_minutes_valdai: 45,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'MIRROR_REPLACE',
    name: 'Замена зеркала',
    category: 'Кузов',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'WIPER_MECH',
    name: 'Замена трапеции дворников',
    category: 'Кузов',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'HEATER_CORE',
    name: 'Замена радиатора печки',
    category: 'Кузов',
    norm_minutes: 240,
    norm_minutes_valdai: 300,
    default_price_client: '6000',
    internal_cost_rate: '3000',
  },
  {
    code: 'HEATER_FAN',
    name: 'Замена вентилятора печки',
    category: 'Кузов',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'AC_CHARGE',
    name: 'Заправка кондиционера',
    category: 'Кузов',
    norm_minutes: 60,
    norm_minutes_valdai: 60,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'AC_COMPRESSOR',
    name: 'Замена компрессора кондиционера',
    category: 'Кузов',
    norm_minutes: 180,
    norm_minutes_valdai: 210,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  // Выхлопная система
  {
    code: 'EXHAUST_MUFFLER',
    name: 'Замена глушителя',
    category: 'Выхлоп',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'EXHAUST_PIPE',
    name: 'Замена приёмной трубы',
    category: 'Выхлоп',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  {
    code: 'EXHAUST_GASKET',
    name: 'Замена прокладки выпускного коллектора',
    category: 'Выхлоп',
    norm_minutes: 90,
    norm_minutes_valdai: 120,
    default_price_client: '2250',
    internal_cost_rate: '1125',
  },
  {
    code: 'EXHAUST_FLEX',
    name: 'Замена гофры глушителя',
    category: 'Выхлоп',
    norm_minutes: 60,
    norm_minutes_valdai: 90,
    default_price_client: '1500',
    internal_cost_rate: '750',
  },
  // Топливная
  {
    code: 'FUEL_PUMP',
    name: 'Замена топливного насоса',
    category: 'Топливная',
    norm_minutes: 180,
    norm_minutes_valdai: 240,
    default_price_client: '4500',
    internal_cost_rate: '2250',
  },
  {
    code: 'FUEL_TANK',
    name: 'Замена топливного бака',
    category: 'Топливная',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'FUEL_LINES',
    name: 'Замена топливных магистралей',
    category: 'Топливная',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  // Шины
  {
    code: 'TYRE_MOUNT_SET',
    name: 'Шиномонтаж (комплект 4 колеса)',
    category: 'Шины',
    norm_minutes: 120,
    norm_minutes_valdai: 150,
    default_price_client: '3000',
    internal_cost_rate: '1500',
  },
  {
    code: 'TYRE_MOUNT_ONE',
    name: 'Шиномонтаж (1 колесо)',
    category: 'Шины',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
  {
    code: 'TYRE_BALANCE',
    name: 'Балансировка колеса',
    category: 'Шины',
    norm_minutes: 15,
    norm_minutes_valdai: 15,
    default_price_client: '375',
    internal_cost_rate: '188',
  },
  {
    code: 'TYRE_REPAIR',
    name: 'Ремонт прокола колеса',
    category: 'Шины',
    norm_minutes: 30,
    norm_minutes_valdai: 30,
    default_price_client: '750',
    internal_cost_rate: '375',
  },
];

async function main() {
  console.log(`Seeding ${works.length} work catalog entries...`);

  for (const w of works) {
    const { error } = await (supabase.from('work_catalog') as any).upsert(
      {
        code: w.code,
        name: w.name,
        category: w.category,
        norm_minutes: w.norm_minutes,
        norm_minutes_valdai: w.norm_minutes_valdai,
        default_price_client: w.default_price_client,
        internal_cost_rate: w.internal_cost_rate,
        is_active: true,
      },
      { onConflict: 'code' },
    );

    if (error) {
      console.error(`  FAIL ${w.code}: ${error.message}`);
    } else {
      console.log(`  OK   ${w.code}: ${w.name}`);
    }
  }

  console.log('Done.');
}

main().catch(console.error);
